#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

NAME=suricata-release
ENV_FILE=/etc/default/suricata-release
COMMAND=/opt/suricata/current/bin/suricata-start

start_service() {
  [ -x "$COMMAND" ] || return 1

  if [ -r "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  fi

  procd_open_instance
  procd_set_param command "$COMMAND"
  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
